### ISSUE TITLE
--dot and --graph doesn't work

### ISSUE THREAD

**Issue by orlovol** [Karkunow/import.io#2]
Any of the following commands:
```
$escript importio -rf "$FLOW/lib, $FLOW" -f sandbox/hello -dp 6 --dot
$escript importio -rf "$FLOW/lib, $FLOW" -f sandbox/hello -dp 6 -oi --graph
```
Result in this error:
```
'Calculating imports structure' took 0.026326s
** (ArgumentError) argument error: nil
    (importio) lib/importio.ex:97: Importio.save_result/3
    (stdlib) timer.erl:197: :timer.tc/3
    (importio) lib/benchmark.ex:13: Benchmark.benchmark/4
    (importio) lib/importio.ex:28: Importio.main/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by Karkunow** [comment]
@hey-sancho, must be fixed now. Download new binary from the server (I updated it inside zip file).

**Comment by orlovol** [comment]
@Karkunow it works, thanks!
